# Generated by Django 4.0.4 on 2022-07-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parachute_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatName', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ray_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('patien_id', models.IntegerField(null=True)),
                ('doc_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='patien_id',
        ),
    ]
