# Generated by Django 4.0.4 on 2022-07-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_parachute_material_ray_report_remove_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parachute_material',
            name='MatName',
            field=models.CharField(default='zzz', max_length=20),
        ),
    ]
