# Generated by Django 4.0.4 on 2022-07-12 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_spe_id'),
        ('patients', '0002_alter_patients_fname_alter_patients_lname'),
        ('reports', '0005_alter_ray_report_doc_id_alter_ray_report_patien_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ray_report',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='ray_report',
            name='patien_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='mat_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_id',
        ),
        migrations.AddField(
            model_name='report',
            name='MatName',
            field=models.CharField(default='zzz', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='doc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='report',
            name='patien_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.DeleteModel(
            name='Parachute_material',
        ),
        migrations.DeleteModel(
            name='Ray_report',
        ),
    ]
