# Generated by Django 4.0.4 on 2022-07-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_imagepathstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ImagePathstring',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
