# Generated by Django 4.0.4 on 2022-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_report_imagepathstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ImagePathstring',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d'),
        ),
    ]
