# Generated by Django 4.0.4 on 2022-07-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=20, null=True)),
                ('LName', models.CharField(max_length=20, null=True)),
                ('Gender', models.CharField(max_length=20, null=True)),
                ('BirthYear', models.DateField(null=True)),
                ('Weight', models.IntegerField(null=True)),
                ('CreditNumber', models.IntegerField(null=True)),
                ('Address', models.CharField(max_length=20, null=True)),
                ('Phon', models.CharField(max_length=20, null=True)),
                ('SocialStatus', models.CharField(max_length=20, null=True)),
                ('MedicalHistory', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
