# Generated by Django 4.0.4 on 2022-07-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='FName',
            field=models.CharField(default='zzz', max_length=20),
        ),
        migrations.AlterField(
            model_name='patients',
            name='LName',
            field=models.CharField(default='zzz', max_length=20),
        ),
    ]
