# Generated by Django 4.0.4 on 2022-07-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_spe_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'doctor'},
        ),
    ]
